version: "3.0"

volumes:
  er-mongo-keys:
  er-mongo-data-0:
  er-mongo-data-1:
  er-mongo-data-2:
  er-mongo-data-3:

networks:
  er-replica-set:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.5.0/24

services:

  er-mongo-keys:
    image: depop/openssl-bats
    volumes:
      - er-mongo-keys:/mongo-conf
    command: 'bash -c "openssl rand -base64 741 > /mongo-conf/mongodb-keyfile; chmod 600 /mongo-conf/mongodb-keyfile; chown 999 /mongo-conf/mongodb-keyfile"'

  # Primary
  er-mongo-primary:
    image: mongo:latest
    volumes:
      - er-mongo-keys:/opt/keyfile
      - er-mongo-data-0:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27017:27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet er-replica-set'
    depends_on:
        - er-mongo-keys
    networks:
      er-replica-set:
  
  # Worker 1
  er-mongo-worker-1:
    image: mongo:latest
    volumes:
      - er-mongo-keys:/opt/keyfile
      - er-mongo-data-1:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27018:27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet er-replica-set'
    depends_on:
        - er-mongo-keys
    networks:
      er-replica-set:
  
  # Worker 2
  er-mongo-worker-2:
    image: mongo:latest
    volumes:
      - er-mongo-keys:/opt/keyfile
      - er-mongo-data-2:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27019:27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet er-replica-set'
    depends_on:
        - er-mongo-keys
    networks:
      er-replica-set:
  
  # Worker 3
  er-mongo-worker-3:
    image: mongo:latest
    volumes:
      - er-mongo-keys:/opt/keyfile
      - er-mongo-data-3:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27020:27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet er-replica-set'
    depends_on:
        - er-mongo-keys
    networks:
      er-replica-set: